"""add entry external identity

Revision ID: 71e5e837ff01
Revises: 7d1a55df4aca
Create Date: 2026-09-03 10:35:06.249818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71e5e837ff01'
down_revision: Union[str, Sequence[str], None] = '7d1a55df4aca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('provider', sa.String(length=50), nullable=True))
    op.add_column('entries', sa.Column('external_id', sa.String(length=255), nullable=True))
    op.create_unique_constraint('uq_entries_user_provider_external_id', 'entries', ['user_id', 'provider', 'external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_entries_user_provider_external_id', 'entries', type_='unique')
    op.drop_column('entries', 'external_id')
    op.drop_column('entries', 'provider')
    # ### end Alembic commands ###
